'use client';
import { useEffect, useState } from 'react';

type SectionKey='problem'|'solution'|'methodology'|'findings'|'futureResearch';
type Section={text:string;images:string[]};
type ProjectDraft={id:string;title:string;subtitle:string;category:string;year:string;role:string;timeline:string;institution:string;tools:string;coverImage:string;linkLabel:string;linkUrl:string;status:'draft'|'published'|'archived';sections:Record<SectionKey,Section>};
const sectionLabels:Record<SectionKey,string>={problem:'Problem',solution:'Solution',methodology:'Methodology',findings:'Findings',futureResearch:'Future research'};
const emptySections=():Record<SectionKey,Section>=>({problem:{text:'',images:[]},solution:{text:'',images:[]},methodology:{text:'',images:[]},findings:{text:'',images:[]},futureResearch:{text:'',images:[]}});
const starters:ProjectDraft[]=[
  {id:'museum',title:'A museum visit that begins before the doors open',subtitle:'Reimagining discovery for visitors who want more than a floor map.',category:'UI/UX Design',year:'2025',role:'Research · Product strategy · Interface design',timeline:'12 weeks',institution:'National Gallery Singapore',tools:'Figma · Maze · Dovetail',coverImage:'/uiux-3d.png',linkLabel:'',linkUrl:'',status:'published',sections:emptySections()},
  {id:'voices',title:'The quiet signals behind student belonging',subtitle:'A mixed-method study turning overlooked campus moments into actionable evidence.',category:'Research',year:'2025',role:'Study design · Interviews · Synthesis',timeline:'10 weeks',institution:'University Student Experience Team',tools:'Dovetail · Qualtrics · Miro',coverImage:'/research-3d.png',linkLabel:'',linkUrl:'',status:'published',sections:emptySections()},
  {id:'studio',title:'A design studio that teaches through doing',subtitle:'Transforming passive slideware into an active, feedback-rich learning journey.',category:'Instructional Design',year:'2024',role:'Learning architecture · Facilitation · Media',timeline:'8 weeks',institution:'Learning & Development Studio',tools:'Figma · PowerPoint · Articulate',coverImage:'/learning-3d.png',linkLabel:'',linkUrl:'',status:'draft',sections:emptySections()},
  {id:'trust',title:'Designing trust into an unfamiliar service',subtitle:'Research and interface decisions for a high-stakes first-use experience.',category:'Research + UI/UX',year:'2024',role:'Discovery · Service blueprint · UX writing',timeline:'9 weeks',institution:'Digital Service Team',tools:'Figma · Miro · Maze',coverImage:'/research-3d.png',linkLabel:'',linkUrl:'',status:'published',sections:emptySections()},
];

export default function AdminDashboard({displayName,signOutPath}:{displayName:string;signOutPath:string}){
  const [projects,setProjects]=useState(starters),[editing,setEditing]=useState<ProjectDraft|null>(null),[view,setView]=useState<'projects'|'resume'>('projects'),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[resumeName,setResumeName]=useState('No résumé selected');
  useEffect(()=>{fetch('/api/admin/projects').then(response=>response.ok?response.json():[]).then((saved:ProjectDraft[])=>{if(saved.length)setProjects(saved)}).catch(()=>{})},[]);
  const patch=(values:Partial<ProjectDraft>)=>setEditing(current=>current?{...current,...values}:current);
  const upload=async(file:File,kind:'image'|'resume')=>{const form=new FormData();form.append('file',file);const response=await fetch(kind==='resume'?'/api/admin/resume':'/api/admin/upload',{method:'POST',body:form});if(!response.ok)throw new Error('Upload failed');return response.json() as Promise<{url:string;name:string}>};
  const uploadCover=async(file?:File)=>{if(!file)return;setMessage('Uploading cover…');try{const result=await upload(file,'image');patch({coverImage:result.url});setMessage('Cover uploaded')}catch{setMessage('Could not upload that image')}};
  const uploadSectionImages=async(key:SectionKey,files:FileList|null)=>{if(!files||!editing)return;setMessage('Uploading images…');try{const results=await Promise.all(Array.from(files).map(file=>upload(file,'image')));setEditing(current=>current?{...current,sections:{...current.sections,[key]:{...current.sections[key],images:[...current.sections[key].images,...results.map(item=>item.url)]}}}:current);setMessage(`${results.length} image${results.length===1?'':'s'} added`)}catch{setMessage('One or more images could not be uploaded')}};
  const save=async(status:ProjectDraft['status']=editing?.status||'draft')=>{if(!editing)return;setSaving(true);setMessage('Saving…');try{const payload={...editing,status};const response=await fetch(`/api/admin/projects/${encodeURIComponent(editing.id)}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error();setProjects(items=>items.some(item=>item.id===payload.id)?items.map(item=>item.id===payload.id?payload:item):[payload,...items]);setEditing(payload);setMessage(status==='published'?'Published changes saved':'Draft saved')}catch{setMessage('Changes could not be saved')}finally{setSaving(false)}};
  const uploadResume=async(file?:File)=>{if(!file)return;setResumeName(file.name);setMessage('Uploading résumé…');try{await upload(file,'resume');setMessage('Latest résumé is now live')}catch{setMessage('Résumé upload failed')}};
  return <main className="admin-shell">
    <header className="admin-header"><div><a href="/" className="admin-mark">J<span>•</span></a><p>PORTFOLIO CONTROL ROOM</p></div><div><span>{displayName}</span><a href={signOutPath}>Sign out</a></div></header>
    {editing?<section className="editor-shell"><header className="editor-head"><div><button type="button" onClick={()=>{setEditing(null);setMessage('')}}>← Projects</button><p>EDIT PROJECT</p><h1>{editing.title||'Untitled project'}</h1></div><div><span aria-live="polite">{message}</span><button type="button" onClick={()=>save('draft')} disabled={saving}>Save draft</button><button className="publish" type="button" onClick={()=>save('published')} disabled={saving}>Publish</button></div></header><form className="project-editor" onSubmit={event=>{event.preventDefault();save()}}>
      <section className="editor-card"><div className="editor-card-title"><span>01</span><div><h2>Basic information</h2><p>The details shown at the top of your project article.</p></div></div><div className="editor-fields"><label className="wide">Project title<input value={editing.title} onChange={e=>patch({title:e.target.value})}/></label><label className="wide">Subtitle / short description<textarea rows={3} value={editing.subtitle} onChange={e=>patch({subtitle:e.target.value})}/></label><label>Category<input value={editing.category} onChange={e=>patch({category:e.target.value})}/></label><label>Year<input value={editing.year} onChange={e=>patch({year:e.target.value})}/></label><label>My role<textarea rows={2} value={editing.role} onChange={e=>patch({role:e.target.value})}/></label><label>Timeline<input value={editing.timeline} onChange={e=>patch({timeline:e.target.value})}/></label><label>Institution<input value={editing.institution} onChange={e=>patch({institution:e.target.value})}/></label><label>Tools used<input value={editing.tools} onChange={e=>patch({tools:e.target.value})}/></label><label className="wide upload-field">Cover image<input type="file" accept="image/*" onChange={e=>uploadCover(e.target.files?.[0])}/>{editing.coverImage&&<span>Current cover: {editing.coverImage.split('/').pop()}</span>}</label></div></section>
      <section className="editor-card"><div className="editor-card-title"><span>02</span><div><h2>Article sections</h2><p>Every section is optional. Add only what helps tell this project’s story.</p></div></div><div className="article-sections">{(Object.keys(sectionLabels) as SectionKey[]).map((key,index)=><fieldset key={key}><legend><span>{String(index+1).padStart(2,'0')}</span>{sectionLabels[key]} <small>Optional</small></legend><textarea rows={7} placeholder={`Write about the ${sectionLabels[key].toLowerCase()}…`} value={editing.sections[key].text} onChange={e=>setEditing(current=>current?{...current,sections:{...current.sections,[key]:{...current.sections[key],text:e.target.value}}}:current)}/><div className="section-images">{editing.sections[key].images.map((image,index)=><div key={image}><img src={image} alt=""/><button type="button" aria-label="Remove image" onClick={()=>setEditing(current=>current?{...current,sections:{...current.sections,[key]:{...current.sections[key],images:current.sections[key].images.filter((_,i)=>i!==index)}}}:current)}>×</button></div>)}<label>＋ Add images<input type="file" accept="image/*" multiple onChange={e=>uploadSectionImages(key,e.target.files)}/></label></div></fieldset>)}</div></section>
      <section className="editor-card"><div className="editor-card-title"><span>03</span><div><h2>External link</h2><p>Link to a live website, paper, document or publication.</p></div></div><div className="editor-fields"><label>Link text<input placeholder="View the published project" value={editing.linkLabel} onChange={e=>patch({linkLabel:e.target.value})}/></label><label>URL<input type="url" placeholder="https://" value={editing.linkUrl} onChange={e=>patch({linkUrl:e.target.value})}/></label></div></section>
    </form></section>:<><section className="admin-welcome"><div><p>PRIVATE WORKSPACE / OWNER ONLY</p><h1>Good to see you,<br/><em>Julfendi.</em></h1></div><button type="button" onClick={()=>setEditing({...starters[0],id:`project-${Date.now()}`,title:'',subtitle:'',status:'draft',sections:emptySections()})}>＋ New project</button></section><section className="admin-grid"><aside><button className={view==='projects'?'active':''} onClick={()=>setView('projects')}>Projects <span>{projects.length}</span></button><button className={view==='resume'?'active':''} onClick={()=>setView('resume')}>Résumé</button><a href="/">← View public site</a></aside>{view==='projects'?<div className="admin-panel"><div className="admin-panel-head"><div><h2>Your projects</h2><p>Choose any project to edit its article and media.</p></div></div>{projects.map((project,index)=><button className={`admin-project ${index===0?'featured':''}`} key={project.id} onClick={()=>setEditing(project)}><div className={`admin-thumb ${['purple','blue','pink','green'][index%4]}`}>{String(index+1).padStart(2,'0')}</div><div><span>{project.status.toUpperCase()}</span><h3>{project.title}</h3><p>{project.category} · {project.year}</p></div><b>Edit →</b></button>)}</div>:<div className="admin-panel resume-admin"><p className="section-kicker">DOWNLOADABLE FILE</p><h2>Résumé</h2><p>Upload a PDF to replace the résumé linked from the public home screen. The download link stays the same, so visitors will always receive the newest version.</p><label>Choose latest résumé<input type="file" accept="application/pdf,.pdf" onChange={e=>uploadResume(e.target.files?.[0])}/></label><strong>{resumeName}</strong><span aria-live="polite">{message}</span></div>}</section></>}
  </main>;
}
