'use client';
import { Fragment, useEffect, useRef, useState } from 'react';

const roles = [
  { name:'Research', className:'blue', image:'/research-3d.png', line:'', meta:'Qualitative · Mixed methods', font:'grotesk' },
  { name:'UI/UX Design', className:'purple', image:'/uiux-3d.png', line:'', meta:'Strategy · Systems · Prototyping', font:'grotesk' },
  { name:'Instructional Design', className:'pink', image:'/learning-3d.png', line:'', meta:'Curriculum · Facilitation · Media', font:'grotesk' },
];
const defaultProjects = [
  { id:'museum', number:'01', category:'UI/UX DESIGN', year:'2025', title:'A museum visit that begins before the doors open', intro:'Reimagining discovery for visitors who want more than a floor map.', color:'#7256ff', accent:'#c7ff4f', image:'/uiux-3d.png', responsibility:'Research · Product strategy · Interface design', tools:'Figma · Maze · Dovetail', institution:'National Gallery Singapore', timeline:'12 weeks', challenge:'Visitors arrived curious but overwhelmed. The experience needed to turn a sprawling collection into a personal route—without asking people to plan like experts.', approach:'I combined intercept interviews, journey mapping and rapid mobile prototypes. The resulting system starts with intent, not departments: “surprise me,” “I have 45 minutes,” or “show me something strange.”', impact:'The tested prototype cut route-planning time by 42% and helped first-time visitors describe the collection with greater confidence.' },
  { id:'voices', number:'02', category:'RESEARCH', year:'2025', title:'The quiet signals behind student belonging', intro:'A mixed-method study turning overlooked campus moments into actionable evidence.', color:'#1674ff', accent:'#75f4ff', image:'/research-3d.png', responsibility:'Study design · Interviews · Synthesis', tools:'Dovetail · Qualtrics · Miro', institution:'University Student Experience Team', timeline:'10 weeks', challenge:'Survey scores showed where belonging was low, but not why. The team needed the texture behind the numbers before investing in new programs.', approach:'I designed diary prompts and semi-structured interviews, then mapped recurring moments of friction and connection across the first twelve weeks.', impact:'Findings shaped three low-cost interventions and a new onboarding measurement framework adopted for the following intake.' },
  { id:'studio', number:'03', category:'INSTRUCTIONAL DESIGN', year:'2024', title:'A design studio that teaches through doing', intro:'Transforming passive slideware into an active, feedback-rich learning journey.', color:'#f1439a', accent:'#ffca4b', image:'/learning-3d.png', responsibility:'Learning architecture · Facilitation · Media', tools:'Figma · PowerPoint · Articulate', institution:'Learning & Development Studio', timeline:'8 weeks', challenge:'A four-hour workshop relied on dense presentation slides and left learners with little opportunity to practise.', approach:'I rebuilt the experience around short demonstrations, guided challenges, peer critique and reusable job aids. Every activity mapped to an observable skill.', impact:'Completion rose to 94%, while post-session confidence increased by 31 percentage points across two cohorts.' },
  { id:'trust', number:'04', category:'RESEARCH + UI/UX', year:'2024', title:'Designing trust into an unfamiliar service', intro:'Research and interface decisions for a high-stakes first-use experience.', color:'#00a98f', accent:'#c8ff65', image:'/research-3d.png', responsibility:'Discovery · Service blueprint · UX writing', tools:'Figma · Miro · Maze', institution:'Digital Service Team', timeline:'9 weeks', challenge:'People hesitated at the moment of commitment because the service asked for sensitive information before explaining what happened next.', approach:'I traced trust gaps across the journey, prototyped progressive disclosure patterns and tested language at the decision points that carried the most anxiety.', impact:'The revised concept improved task completion and reduced perceived risk in moderated evaluation.' },
];
const projectFilters = ['All','UI/UX Design','Research','Instructional Design'];
const stickerBases = [
  {type:'nature',label:'Nature',images:['/stickers/nature.png']}, {type:'book',label:'Education',images:['/stickers/book.png']},
  {type:'ai',label:'AI',images:['/stickers/ai.png']}, {type:'speech',label:'Language',images:['/stickers/speech.png']},
];
const starterStickers = [0,1].flatMap(copy=>stickerBases.map((item,index)=>({...item,id:`${item.type}-${copy}`,x:5+(index%2)*25+copy*6,y:15+Math.floor(index/2)*42+copy*7})));
const stickerRecipes:Record<string,{type:string,label:string,images:string[]}> = {
  'book+nature':{type:'novel-classroom-concepts',label:'Novel Classroom Concepts',images:['/stickers/reading-space-in-nature.png']},
  'ai+book':{type:'ai-assisted-practice',label:'AI-Assisted Practice',images:['/stickers/ai-assisted-learning.png']},
  'book+speech':{type:'diverse-learning-community',label:'Diverse Learning Community',images:['/stickers/story-circle.png']},
  'book+book':{type:'inclusive-library',label:'Inclusive Library',images:['/stickers/library.png']},
  'nature+nature':{type:'nature-hub',label:'Nature Hub',images:['/stickers/nature-hub.png']},
  'ai+nature':{type:'futuristic-learning-space',label:'Futuristic Learning Space',images:['/stickers/nature.png','/stickers/ai.png']},
  'nature+speech':{type:'cultural-exchange-spring',label:'Cultural Exchange Spring',images:['/stickers/cultural-exchange-sites.png']},
  'ai+ai':{type:'agentic-ai',label:'Agentic AI',images:['/stickers/agentic-ai.png']},
  'ai+speech':{type:'ai-conversation-partner',label:'AI Conversation Partner',images:['/stickers/ai.png','/stickers/speech.png']},
  'speech+speech':{type:'social-connection',label:'Social Connection',images:['/stickers/connection.png']},
};
const initialNotes = [
  {id:'note-1',x:68,y:8,open:false,text:'How might non-Western philosophies inspire new ways of learning, teaching, and designing educational spaces?'},
  {id:'note-2',x:82,y:27,open:false,text:'How might nature, culture, and community become part of the learning environment?'},
  {id:'note-3',x:69,y:51,open:false,text:'What is the value of education, beyond preparing people for work?'},
  {id:'note-4',x:82,y:70,open:false,text:'How might immersive technology strengthen relationships between students and their teachers and students and their peers?'},
];
const splitArticleParagraphs=(text:string)=>text.split(/\n\s*\n/).map(paragraph=>paragraph.trim()).filter(Boolean);
function PublishedSectionFlow({section}:{section:any}){const paragraphs=splitArticleParagraphs(section.text||'');const images=(section.images||[]).map((image:any)=>typeof image==='string'?{url:image,size:'full',align:'center',placement:'after'}:{placement:'after',...image});const imagesAt=(placement:'before'|'after'|number)=>images.map((image:any,index:number)=>image.placement===placement?<img key={`${image.url}-${index}`} className={`size-${image.size} align-${image.align} placement-${typeof placement==='number'?'paragraph':placement}`} src={image.url} alt=""/>:null);return <div className="published-flow">{imagesAt('before')}{paragraphs.map((paragraph,index)=><Fragment key={`${index}-${paragraph.slice(0,20)}`}>{imagesAt(index)}<p>{paragraph}</p></Fragment>)}{imagesAt('after')}</div>}
function ResearchPaperAnimation(){return <div className="research-paper-animation" aria-hidden="true"><div className="paper-sheet"><strong className="paper-piece paper-title">Research Title</strong><span className="paper-piece paper-authors">Authors</span><strong className="paper-piece paper-abstract">Abstract</strong><span className="paper-piece paper-lines"><i/><i/><i/><i/><i/></span><span className="paper-cursor">➤</span></div></div>}
function UiUxAnimation(){return <div className="card-demo-animation ui-demo" aria-hidden="true"><div className="demo-sheet ui-sheet"><div className="browser-bar"><i/><i/><i/></div><div className="ui-copy"><strong>Welcome</strong><span/><span/><b/><b/></div><div className="ui-image-card"><span>◇</span></div><span className="demo-cursor ui-cursor">➤</span></div></div>}
function InstructionalAnimation(){return <div className="card-demo-animation instruction-demo" aria-hidden="true"><div className="demo-sheet instruction-sheet"><strong>Follow these Steps</strong><i className="instruction-rule"/><div className="steps"><b>1</b><b className="moving-step">2</b><b>3</b></div><span className="demo-cursor instruction-cursor">➤</span></div></div>}

export default function Home(){
  const [role,setRole]=useState(0),[project,setProject]=useState(0),[dark,setDark]=useState(false),[paused,setPaused]=useState(false),[activeSection,setActiveSection]=useState('home'),[projectFilter,setProjectFilter]=useState('All'),[focusView,setFocusView]=useState(false),[shared,setShared]=useState(false),[contactCopied,setContactCopied]=useState(false); const touchX=useRef(0);
  const [projects,setProjects]=useState<any[]>(defaultProjects);
  const [stickers,setStickers]=useState(starterStickers),[dragging,setDragging]=useState<string|null>(null),[puff,setPuff]=useState<{x:number,y:number}|null>(null),[notes,setNotes]=useState(initialNotes),[draggingNote,setDraggingNote]=useState<string|null>(null),[boardLayers,setBoardLayers]=useState<Record<string,number>>({}); const stickerBoard=useRef<HTMLDivElement>(null),dragOffset=useRef({x:0,y:0}),noteMoved=useRef(false),layerCounter=useRef(20);
  useEffect(()=>{if(localStorage.getItem('julfendi-theme')==='dark')setDark(true)},[]);
  useEffect(()=>{if(paused)return;const timer=setTimeout(()=>setRole(v=>(v+1)%roles.length),7800);return()=>clearTimeout(timer)},[paused,role]);
  useEffect(()=>{localStorage.setItem('julfendi-theme',dark?'dark':'light')},[dark]);
  useEffect(()=>{fetch('/api/projects').then(response=>response.ok?response.json():[]).then(saved=>{if(!Array.isArray(saved)||!saved.length)return;setProjects(saved.map((item:any,index:number)=>{const fallback=defaultProjects.find(project=>project.id===item.id)||defaultProjects[index%defaultProjects.length];return {...fallback,...item,number:String(index+1).padStart(2,'0'),intro:item.subtitle||fallback.intro,image:item.coverImage||fallback.image,responsibility:item.role||fallback.responsibility,challenge:item.sections?.problem?.text||fallback.challenge,approach:item.sections?.solution?.text||fallback.approach,impact:item.sections?.findings?.text||fallback.impact}}))}).catch(()=>{})},[]);
  useEffect(()=>{const query=matchMedia('(max-width: 800px)');const arrangeNotes=()=>setNotes(query.matches?initialNotes.map((note,index)=>({...note,x:[7,54,7,54][index],y:[71,71,85,85][index]})):initialNotes);arrangeNotes();query.addEventListener('change',arrangeNotes);return()=>query.removeEventListener('change',arrangeNotes)},[]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActiveSection(visible.target.id)},{rootMargin:'-18% 0px -62% 0px',threshold:[0,.2,.5,.8]});['home','portfolio','about','contact'].forEach(id=>{const section=document.getElementById(id);if(section)observer.observe(section)});return()=>observer.disconnect()},[]);
  const current=roles[role],selected=projects[project],moveRole=(d:number)=>setRole(v=>(v+d+roles.length)%roles.length),visibleProjects=projects.map((item,index)=>({item,index})).filter(({item})=>projectFilter==='All'||item.category.toLowerCase().includes(projectFilter.toLowerCase().replace(' design',''))),shareProject=async()=>{try{const url=`${location.origin}${location.pathname}#project-${selected.id}`;if(navigator.share)await navigator.share({title:selected.title,text:selected.intro,url});else await navigator.clipboard.writeText(url);setShared(true);setTimeout(()=>setShared(false),1800)}catch{}};
  const bringBoardItemForward=(id:string)=>{layerCounter.current+=1;setBoardLayers(layers=>({...layers,[id]:layerCounter.current}))};
  const beginStickerDrag=(event:React.PointerEvent,item:(typeof stickers)[number])=>{if(!stickerBoard.current)return;bringBoardItemForward(item.id);const rect=stickerBoard.current.getBoundingClientRect();dragOffset.current={x:event.clientX-(rect.left+item.x/100*rect.width),y:event.clientY-(rect.top+item.y/100*rect.height)};setDragging(item.id);event.currentTarget.setPointerCapture(event.pointerId)};
  const moveSticker=(event:React.PointerEvent,id:string)=>{if(dragging!==id||!stickerBoard.current)return;const rect=stickerBoard.current.getBoundingClientRect();const x=Math.max(3,Math.min(83,(event.clientX-rect.left-dragOffset.current.x)/rect.width*100));const y=Math.max(5,Math.min(78,(event.clientY-rect.top-dragOffset.current.y)/rect.height*100));setStickers(items=>items.map(item=>item.id===id?{...item,x,y}:item))};
  const endStickerDrag=(id:string)=>{const moving=stickers.find(item=>item.id===id);if(!moving){setDragging(null);return}const target=stickers.filter(item=>item.id!==id).sort((a,b)=>Math.hypot(a.x-moving.x,a.y-moving.y)-Math.hypot(b.x-moving.x,b.y-moving.y))[0];if(target&&Math.hypot(target.x-moving.x,target.y-moving.y)<18){const key=[moving.type,target.type].sort().join('+');const result=stickerRecipes[key];if(result){const x=(moving.x+target.x)/2,y=(moving.y+target.y)/2,newId=`${result.type}-${Date.now()}`;setPuff({x,y});setStickers(items=>items.filter(item=>item.id!==moving.id&&item.id!==target.id));setTimeout(()=>{setStickers(items=>[...items,{id:newId,...result,x,y}]);bringBoardItemForward(newId);setPuff(null)},260)}else{setStickers(items=>items.map(item=>item.id===id?{...item,x:Math.max(3,item.x-4),y:Math.max(5,item.y-2)}:item))}}setDragging(null)};
  const beginNoteDrag=(event:React.PointerEvent,note:(typeof notes)[number])=>{if(!stickerBoard.current)return;bringBoardItemForward(note.id);const rect=stickerBoard.current.getBoundingClientRect();dragOffset.current={x:event.clientX-(rect.left+note.x/100*rect.width),y:event.clientY-(rect.top+note.y/100*rect.height)};noteMoved.current=false;setDraggingNote(note.id);event.currentTarget.setPointerCapture(event.pointerId)};
  const moveNote=(event:React.PointerEvent,id:string)=>{if(draggingNote!==id||!stickerBoard.current)return;const rect=stickerBoard.current.getBoundingClientRect();const x=Math.max(3,Math.min(84,(event.clientX-rect.left-dragOffset.current.x)/rect.width*100));const y=Math.max(3,Math.min(76,(event.clientY-rect.top-dragOffset.current.y)/rect.height*100));noteMoved.current=true;setNotes(items=>items.map(item=>item.id===id?{...item,x,y}:item))};
  return <main className={`site-shell ${dark?'dark':''}`}>
    <nav className="nav-shell" aria-label="Primary navigation"><a className="wordmark" href="#home" aria-label="Julfendi home">J<span>•</span></a><div className="nav-links"><a className={activeSection==='home'?'is-active':''} href="#home">Home</a><a className={activeSection==='portfolio'?'is-active':''} href="#portfolio">Portfolio</a><a className={activeSection==='about'?'is-active':''} href="#about">About me</a><a className={activeSection==='contact'?'is-active':''} href="#contact">Work with me</a></div><button className="theme-toggle" type="button" onClick={()=>setDark(v=>!v)} aria-label={`Switch to ${dark?'bright':'dark'} mode`} aria-pressed={dark}><span>{dark?'Dark':'Light'}</span><i aria-hidden="true" /></button></nav>
    <section id="home" className={`hero hero-${current.className}`} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)} onTouchStart={e=>touchX.current=e.touches[0].clientX} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-touchX.current;if(Math.abs(delta)>45)moveRole(delta<0?1:-1)}}>
      <div className="hero-heading"><h1>Hi, I’m Julfendi.</h1><p>Let’s collaborate in</p></div>
      <div className="hero-stage" aria-live="polite"><button className="side-arrow side-arrow-left" type="button" onClick={()=>moveRole(-1)} aria-label="Previous discipline"><span aria-hidden="true">‹</span></button><div className="role-orbit" aria-hidden="true">{roles.map((item,i)=><div key={item.name} className={`glass-placeholder ${i===role?'is-active':i===(role+roles.length-1)%roles.length?'is-prev':'is-next'}`}>{i===role&&item.name==='Research'?<ResearchPaperAnimation/>:i===role&&item.name==='UI/UX Design'?<UiUxAnimation/>:i===role&&item.name==='Instructional Design'?<InstructionalAnimation/>:null}</div>)}</div><button className="side-arrow side-arrow-right" type="button" onClick={()=>moveRole(1)} aria-label="Next discipline"><span aria-hidden="true">›</span></button><div className="role-details"><p className={`role-title ${current.font}`}>{current.name}</p>{current.line&&<p className="role-copy">{current.line}</p>}<p className="role-meta">{current.meta}</p></div></div>
      <div className="hero-bottom"><div className="carousel-nav" aria-label="Choose a discipline"><div>{roles.map((r,i)=><button key={r.name} className={i===role?'active':''} onClick={()=>setRole(i)} aria-label={`Show ${r.name}`}>{r.name}</button>)}</div></div><div className="hero-actions"><a className="primary-cta" href="#portfolio">View my projects</a><a className="resume-link" href="/api/resume"><span>⇩</span> Download résumé</a></div></div>
    </section>
    <section id="portfolio" className="projects-section" style={{'--project':selected.color,'--project-accent':selected.accent} as React.CSSProperties}>
      <div className={`project-console ${focusView?'focus-view':''}`}><header className="section-heading"><h2>Selected projects</h2><div className="project-filters" aria-label="Filter projects by category">{projectFilters.map(filter=><button key={filter} type="button" className={projectFilter===filter?'active':''} aria-pressed={projectFilter===filter} onClick={()=>{setProjectFilter(filter);const first=projects.findIndex(item=>filter==='All'||item.category.toLowerCase().includes(filter.toLowerCase().replace(' design','')));if(first>=0)setProject(first)}}>{filter}</button>)}</div></header><div className="case-pane"><div className="case-toolbar"><div className="reader-facts"><span className="reader-badge">{selected.category}</span><span>◷ {`6 min read`}</span><span>▣ {selected.year}</span></div><div className="reader-actions"><button type="button" onClick={shareProject}>⌯ {shared?'Copied':'Share'}</button><button type="button" className="focus-button" onClick={()=>setFocusView(value=>!value)} aria-pressed={focusView}>⛶ {focusView?'Exit focus':'Focus View'}</button></div></div><article className="case-reader" tabIndex={0} aria-live="polite"><h3>{selected.title}</h3><p className="case-intro">{selected.intro}</p><div className="case-visual"><div className="scanlines"/><img src={selected.image} alt=""/></div><div className="project-overview" aria-label="Project overview"><div><span>My role</span><strong>{selected.responsibility}</strong></div><div><span>Tools used</span><strong>{selected.tools}</strong></div><div><span>Institution</span><strong>{selected.institution}</strong></div><div><span>Timeline</span><strong>{selected.timeline}</strong></div></div><div className="case-copy">{selected.sections?Object.entries(selected.sections).map(([key,section]:any)=>(section.text||section.images?.length)?<section className="published-section" key={key}><p className="copy-label">{key.replace(/([A-Z])/g,' $1')}</p><PublishedSectionFlow section={section}/></section>:null):<><p className="copy-label">The challenge</p><h4>{selected.challenge}</h4><p className="copy-label">The approach</p><p>{selected.approach}</p><blockquote>“Make the invisible parts of an experience visible enough to change.”</blockquote><p className="copy-label">The impact</p><p>{selected.impact}</p></>}{selected.linkUrl&&<a className="project-external-link" href={selected.linkUrl} target="_blank" rel="noreferrer">{selected.linkLabel||'Visit project'} ↗</a>}</div></article></div><aside className="project-selector" aria-label="Choose a project"><div className="selector-rail">{visibleProjects.map(({item,index})=><button key={item.id} onClick={()=>{setProject(index);history.replaceState(null,'',`#project-${item.id}`)}} className={index===project?'active':''} aria-pressed={index===project}><span>{item.number}</span><strong>{item.title}</strong><small>{item.category}</small></button>)}</div></aside></div>
    </section>
    <section id="about" className="about-section"><div className="about-copy"><p className="section-kicker">About me</p><h2>Hi, I am <em>Julfendi.</em></h2><p>I approach design with curiosity, empathy, and a willingness to play with possibilities. I enjoy understanding people and their context, connecting unrelated ideas, and turning those insights into thoughtful experiences.</p><p>I am curious about how culture, nature, technology, and human interaction can reimagine education. I hope to explore learning experiences that are more human, meaningful, and responsive to the world around us.</p></div><div className="about-portrait"><img src="/about-me-vision.gif" alt="People and friendly robots learning, creating and connecting together in nature"/></div><div className="sticker-board" ref={stickerBoard} aria-label="Interactive curiosity board"><div className="board-zone-label board-zone-stickers"><strong>Combine my curiosities</strong><span>Two copies of each—drag one onto another</span></div><div className="board-zone-label board-zone-notes"><strong>Questions on my mind</strong><span>Move or unfold a note</span></div><div className="board-divider" aria-hidden="true"/>{stickers.map(item=><button key={item.id} type="button" className={`interest-sticker ${dragging===item.id?'is-dragging':''}`} style={{left:`${item.x}%`,top:`${item.y}%`,zIndex:boardLayers[item.id]??2} as React.CSSProperties} onPointerDown={event=>beginStickerDrag(event,item)} onPointerMove={event=>moveSticker(event,item.id)} onPointerUp={()=>endStickerDrag(item.id)} aria-label={`${item.label}. Drag to combine.`}><span className={`sticker-art ${item.images.length>1?'is-composite':''}`}>{item.images.map(image=><img key={image} src={image} alt="" draggable={false}/>)}</span><small>{item.label}</small></button>)}{notes.map((note,index)=><button key={note.id} type="button" className={`discussion-note note-${index+1} ${note.open?'is-open':''} ${draggingNote===note.id?'is-dragging':''}`} style={{left:`${note.x}%`,top:`${note.y}%`,zIndex:boardLayers[note.id]??3}} onPointerDown={event=>beginNoteDrag(event,note)} onPointerMove={event=>moveNote(event,note.id)} onPointerUp={()=>{setDraggingNote(null);if(!noteMoved.current)setNotes(items=>items.map(item=>item.id===note.id?{...item,open:!item.open}:item))}} aria-expanded={note.open}><span>{note.open?note.text:`Question ${index+1}`}</span></button>)}{puff&&<span className="sticker-puff" style={{left:`${puff.x}%`,top:`${puff.y}%`}} aria-hidden="true">✦</span>}<button type="button" className="reset-board" onClick={()=>{setStickers(starterStickers);setNotes(initialNotes);setBoardLayers({});layerCounter.current=20;setPuff(null)}}>Reset board ↺</button></div></section>
    <section id="contact" className="contact-section"><div className="contact-intro"><h2>Have a vision to <em>research, design, or teach?</em></h2><p>I am currently open to select staff product design roles, mixed-methods research consultancies, and transformative design projects.</p></div><div className="contact-actions"><h3>Contact me</h3><div className="contact-buttons"><div className="contact-email"><a href="mailto:julfendiv@gmail.com">julfendiv@gmail.com</a><button type="button" onClick={async()=>{await navigator.clipboard.writeText('julfendiv@gmail.com');setContactCopied(true);setTimeout(()=>setContactCopied(false),1600)}}>{contactCopied?'Copied':'Copy'}</button></div><a className="contact-linkedin" href="https://www.linkedin.com/in/julfendiv" target="_blank" rel="noreferrer"><span aria-hidden="true">in</span> LinkedIn ↗</a></div></div></section>
    <footer><span>© 2026 Julfendi</span><span>Designed with curiosity in Singapore</span><a href="/admin">Admin</a></footer>
  </main>
}
