'use client';
import { useEffect, useRef, useState } from 'react';

const roles = [
  { name:'Research', className:'blue', image:'/research-3d.png', line:'Finding the signal inside the noise.', meta:'Qualitative · Mixed methods', font:'grotesk' },
  { name:'UI/UX Design', className:'purple', image:'/uiux-3d.png', line:'Interfaces with clarity, character and purpose.', meta:'Strategy · Systems · Prototyping', font:'grotesk' },
  { name:'Instructional Design', className:'pink', image:'/learning-3d.png', line:'Learning experiences that make ideas click.', meta:'Curriculum · Facilitation · Media', font:'grotesk' },
];
const projects = [
  { id:'museum', number:'01', category:'UI/UX DESIGN', year:'2025', title:'A museum visit that begins before the doors open', intro:'Reimagining discovery for visitors who want more than a floor map.', color:'#7256ff', accent:'#c7ff4f', image:'/uiux-3d.png', responsibility:'Research · Product strategy · Interface design', challenge:'Visitors arrived curious but overwhelmed. The experience needed to turn a sprawling collection into a personal route—without asking people to plan like experts.', approach:'I combined intercept interviews, journey mapping and rapid mobile prototypes. The resulting system starts with intent, not departments: “surprise me,” “I have 45 minutes,” or “show me something strange.”', impact:'The tested prototype cut route-planning time by 42% and helped first-time visitors describe the collection with greater confidence.' },
  { id:'voices', number:'02', category:'RESEARCH', year:'2025', title:'The quiet signals behind student belonging', intro:'A mixed-method study turning overlooked campus moments into actionable evidence.', color:'#1674ff', accent:'#75f4ff', image:'/research-3d.png', responsibility:'Study design · Interviews · Synthesis', challenge:'Survey scores showed where belonging was low, but not why. The team needed the texture behind the numbers before investing in new programs.', approach:'I designed diary prompts and semi-structured interviews, then mapped recurring moments of friction and connection across the first twelve weeks.', impact:'Findings shaped three low-cost interventions and a new onboarding measurement framework adopted for the following intake.' },
  { id:'studio', number:'03', category:'INSTRUCTIONAL DESIGN', year:'2024', title:'A design studio that teaches through doing', intro:'Transforming passive slideware into an active, feedback-rich learning journey.', color:'#f1439a', accent:'#ffca4b', image:'/learning-3d.png', responsibility:'Learning architecture · Facilitation · Media', challenge:'A four-hour workshop relied on dense presentation slides and left learners with little opportunity to practise.', approach:'I rebuilt the experience around short demonstrations, guided challenges, peer critique and reusable job aids. Every activity mapped to an observable skill.', impact:'Completion rose to 94%, while post-session confidence increased by 31 percentage points across two cohorts.' },
  { id:'trust', number:'04', category:'RESEARCH + UI/UX', year:'2024', title:'Designing trust into an unfamiliar service', intro:'Research and interface decisions for a high-stakes first-use experience.', color:'#00a98f', accent:'#c8ff65', image:'/research-3d.png', responsibility:'Discovery · Service blueprint · UX writing', challenge:'People hesitated at the moment of commitment because the service asked for sensitive information before explaining what happened next.', approach:'I traced trust gaps across the journey, prototyped progressive disclosure patterns and tested language at the decision points that carried the most anxiety.', impact:'The revised concept improved task completion and reduced perceived risk in moderated evaluation.' },
];

export default function Home(){
  const [role,setRole]=useState(0),[project,setProject]=useState(0),[dark,setDark]=useState(false),[paused,setPaused]=useState(false); const touchX=useRef(0);
  useEffect(()=>{if(localStorage.getItem('julfendi-theme')==='dark')setDark(true)},[]);
  useEffect(()=>{if(paused)return;const timer=setInterval(()=>setRole(v=>(v+1)%roles.length),3000);return()=>clearInterval(timer)},[paused]);
  useEffect(()=>{localStorage.setItem('julfendi-theme',dark?'dark':'light')},[dark]);
  const current=roles[role],selected=projects[project],moveRole=(d:number)=>setRole(v=>(v+d+roles.length)%roles.length);
  return <main className={`site-shell ${dark?'dark':''}`}>
    <nav className="nav-shell" aria-label="Primary navigation"><a className="wordmark" href="#home" aria-label="Julfendi home">J<span>•</span></a><div className="nav-links"><a className="is-active" href="#home">Home</a><a href="#portfolio">Portfolio</a><a href="#about">About me</a><a href="#contact">Work with me</a></div><button className="theme-toggle" type="button" onClick={()=>setDark(v=>!v)} aria-label={`Switch to ${dark?'bright':'dark'} mode`} aria-pressed={dark}><span>{dark?'Dark':'Light'}</span><i aria-hidden="true" /></button></nav>
    <section id="home" className={`hero hero-${current.className}`} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)} onTouchStart={e=>touchX.current=e.touches[0].clientX} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-touchX.current;if(Math.abs(delta)>45)moveRole(delta<0?1:-1)}}>
      <div className="hero-heading"><h1>Hi, I’m Julfendi.</h1><p>Let’s collaborate in</p></div>
      <div className="hero-stage" aria-live="polite"><div className="role-orbit"><img key={current.image} src={current.image} alt={`${current.name} 3D illustration`}/></div><div className="role-details"><p className={`role-title ${current.font}`}>{current.name}</p><p className="role-copy">{current.line}</p><p className="role-meta">{current.meta}</p></div></div>
      <div className="hero-bottom"><a className="primary-cta" href="#portfolio">View my projects <span>↘</span></a><div className="carousel-nav" aria-label="Role carousel controls"><button type="button" onClick={()=>moveRole(-1)} aria-label="Previous role">←</button><div>{roles.map((r,i)=><button key={r.name} className={i===role?'active':''} onClick={()=>setRole(i)} aria-label={`Show ${r.name}`}/>)}</div><button type="button" onClick={()=>moveRole(1)} aria-label="Next role">→</button></div><a className="resume-link" href="#resume">Download résumé ↗</a></div>
    </section>
    <section id="portfolio" className="projects-section" style={{'--project':selected.color,'--project-accent':selected.accent} as React.CSSProperties}>
      <header className="section-heading"><p>Selected archive / All projects</p><h2>Work, unfolded.</h2><span>Choose a title. Stay in the story.</span></header>
      <div className="project-console"><article className="case-reader" tabIndex={0} aria-live="polite"><div className="case-topline"><span>{selected.category}</span><span>{selected.year}</span><span>PROJECT {selected.number}</span></div><h3>{selected.title}</h3><p className="case-intro">{selected.intro}</p><div className="case-visual"><div className="scanlines"/><img src={selected.image} alt=""/></div><div className="case-meta"><p>MY RESPONSIBILITY</p><strong>{selected.responsibility}</strong></div><div className="case-copy"><p className="copy-label">01 / The challenge</p><h4>{selected.challenge}</h4><p className="copy-label">02 / The approach</p><p>{selected.approach}</p><blockquote>“Make the invisible parts of an experience visible enough to change.”</blockquote><p className="copy-label">03 / The impact</p><p>{selected.impact}</p></div></article><aside className="project-selector" aria-label="Choose a project"><div className="selector-rail">{projects.map((item,i)=><button key={item.id} onClick={()=>{setProject(i);history.replaceState(null,'',`#project-${item.id}`)}} className={i===project?'active':''} aria-pressed={i===project}><span>{item.number}</span><strong>{item.title}</strong><small>{item.category}</small></button>)}</div><p>Scroll titles<br/>or choose directly</p></aside></div>
    </section>
    <section id="about" className="about-section"><p className="section-kicker">About me</p><div><h2>I connect evidence,<br/><em>interfaces</em> and learning.</h2><p>I’m Julfendi—a multidisciplinary designer who turns complex questions into experiences people can understand, use and remember.</p></div><div className="capability-list"><span>01 Research systems</span><span>02 Digital experiences</span><span>03 Learning journeys</span></div></section>
    <section id="contact" className="contact-section"><p>Have a complex idea?</p><h2>Let’s make it<br/><em>click.</em></h2><a href="mailto:hello@julfendi.design">Start a conversation ↗</a></section>
    <footer><span>© 2026 Julfendi</span><span>Designed with curiosity in Singapore</span><a href="/admin">Admin</a></footer>
  </main>
}
